"""empty message

Revision ID: 322e4a46ef70
Revises: c425dfc77519
Create Date: 2023-01-25 21:25:24.989864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322e4a46ef70'
down_revision = 'c425dfc77519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.alter_column('challenge_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.alter_column('challenge_rating',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
